document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'zh-CN\'>");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <title>管理员中心</title>");
document.writeln("    <meta name=\'renderer\' content=\'webkit\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge,chrome=1\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'../statics/lib/layui/css/layui.css\' media=\'all\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'../statics/css/site.css\'>");
document.writeln("    <script src=\'../statics/web.js\'></script>");
document.writeln("    <script src=\'../statics/lib/jquery.min.js\'></script>");
document.writeln("    <script src=\'../statics/lib/layui/layui.all.js\' charset=\'utf-8\'></script>");
document.writeln("    <style>");
document.writeln("        .layui-icon-login-wechat{");
document.writeln("            color: #777;");
document.writeln("        }");
document.writeln("        .layui-this .layui-icon-login-wechat{");
document.writeln("            color: #4C84FF;");
document.writeln("        }");
document.writeln("    </style>");
document.writeln("</head>");
document.writeln("<body class=\'layui-layout-body\'>");
document.writeln("<div id=\'LAY_app\'>");
document.writeln("    <div class=\'layui-layout layui-layout-admin\'>");
document.writeln("        <div class=\'layui-header\'>");
document.writeln("            <div class=\'layui-nav layui-layout-left\'>");
document.writeln("                <span>管理员后台</span>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("        <!-- 侧边菜单 -->");
document.writeln("        <div class=\'layui-side layui-side-menu\' style=\'background-color: #fbfbfb !important; margin-bottom: 60px; \'>");
document.writeln("            <div class=\'layui-side-scroll\'>");
document.writeln("                <ul class=\'layui-nav layui-nav-tree\' >");
document.writeln("");
document.writeln("                    <li class=\'layui-nav-item\'>");
document.writeln("                        <a href=\'./index.html\' >");
document.writeln("                            <i class=\'layui-icon layui-icon-home\'></i>");
document.writeln("                            <cite>主页</cite>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'layui-nav-item\'>");
document.writeln("                        <a href=\'./item.html\'>");
document.writeln("                            <i class=\'layui-icon layui-icon-app\'></i>");
document.writeln("                            <cite>规格列表</cite>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'layui-nav-item\'>");
document.writeln("                        <a href=\'./custom.html\'>");
document.writeln("                            <i class=\'layui-icon layui-icon-app\'></i>");
document.writeln("                            <cite>定制列表</cite>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'layui-nav-item\'>");
document.writeln("                        <a href=\'./photo.html\'>");
document.writeln("                            <i class=\'layui-icon layui-icon-app\'></i>");
document.writeln("                            <cite>保存列表</cite>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'layui-nav-item\'>");
document.writeln("                        <a href=\'./photorecord.html\'>");
document.writeln("                            <i class=\'layui-icon layui-icon-app\'></i>");
document.writeln("                            <cite>行为列表</cite>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                    <li class=\'layui-nav-item\'>");
document.writeln("                        <a href=\'./user.html\'>");
document.writeln("                            <i class=\'layui-icon layui-icon-user\'></i>");
document.writeln("                            <cite>用户列表</cite>");
document.writeln("                        </a>");
document.writeln("                    </li>");
document.writeln("                        <li  class=\'layui-nav-item\'>");
document.writeln("                        <a href=\'./webset.html\'>");
document.writeln("                                <i class=\'layui-icon layui-icon-set\'></i>");
document.writeln("                                <cite>系统设置</cite>");
document.writeln("                            </a>");
document.writeln("                        </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'layui-body\' id=\'LAY_app_body\'>");
document.writeln("         ");